module.exports = {
	CREEP_DEFENCE:"DEFENCE",
	CREEP_OFFENCE:"OFFENCE",
	CREEP_OFFENCE_HEAL:"OFFENCE_HEAL",
	CREEP_WORKER:"WORKER",
	CREEP_WORKER_MINER:"WORKER_MINER",
	CREEP_WORKER_CARRY:"WORKER_CARRY",
	CREEP_HARVESTER:"HARVESTER",
	CREEP_HARVESTER_MINER:"HARVESTER_MINER",
	CREEP_HARVESTER_CARRY:"HARVESTER_CARRY",

	STATE_AMASS:"AMASS",
	STATE_CHECK:"CHECK",
	STATE_HARVEST:"HARVEST",
	STATE_DEFENCE:"DEFENCE",
	STATE_STORE:"STORE",
	STATE_EXPAND:"EXPAND",
	STATE_SPREAD:"SPREAD"
}
